# =============================================================================================== #
# Configuration for welcome - https://github.com/behaviorbot/welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening this issue, maintainers will get back to you as soon as possible!
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks so much for opening your first PR here!
# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request here! :tada: How awesome!
# =============================================================================================== #
# Configuration for request-info - https://github.com/behaviorbot/request-info

# *OPTIONAL* Comment to reply with
# Can be either a string :
requestInfoReplyComment: >
  We would appreciate it if you could provide us with more info about this issue/pr!

requestInfoDefaultTitles:
  - update readme.md
  - updates
  - update
  - up
  - updata
  - add
  - remove
  - fix
  - fix bug

# *OPTIONAL* Label to be added to Issues and Pull Requests with insufficient information given
requestInfoLabelToAdd: Need More Info

# *OPTIONAL* Require Issues to contain more information than what is provided in the issue templates
# Will fail if the issue's body is equal to a provided template
checkIssueTemplate: true
# *OPTIONAL* Require Pull Requests to contain more information than what is provided in the PR template
# Will fail if the pull request's body is equal to the provided template
checkPullRequestTemplate: true
# *OPTIONAL* Add a list of people whose Issues/PRs will not be commented on
# keys must be GitHub usernames
requestInfoUserstoExclude:
  - MHuiG
# =============================================================================================== #
# Configuration for todo-bot - https://github.com/JasonEtco/todo
todo:
  label: '🗒 To-Do'
