name: cdn资源腾讯云cos同步

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: 检出仓库代码
      uses: actions/checkout@master

    - name: 安装腾讯云依赖
      run: |
        sudo pip install coscmd

    - name: 配置腾讯云依赖
      env:
        SECRET_ID: ${{ secrets.TCLOUD_API_ID }}
        SECRET_KEY: ${{ secrets.TCLOUD_API_KEY }}
        BUCKET: ${{ secrets.TCLOUD_BUCKET_NAME }}
        REGION: ${{ secrets.TCLOUD_BUCKET_REGION }}
      run: |
        coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
        tccli configure set secretId $SECRET_ID
        tccli configure set secretKey $SECRET_KEY
        tccli configure set region $REGION

    - name: 上传到腾讯云COS并刷新CDN
      run: |
        coscmd upload -rfs --delete ./static/ /static/
